### ISSUE TITLE
Is ISPC version 1.14.1 really needed ?

### ISSUE THREAD

**Issue by ColinChargyBentley** [OpenImageDenoise/oidn#100]
Hi,
We are using ISPC 1.13.0, we have trouble updating ISPC because we compile on old MacOS (see https://github.com/ispc/ispc/issues/1737 ). Is ISPC 1.14.1 really needed ? What feature of 1.14.1 is needed (and not available in previous version) ?
Regards,
Colin Chargy

**Comment by atafra** [comment]
Hi Colin,
Yes, ISPC 1.13.0 is required because it has a critical bug in handling AVX-512 support. ISPC 1.14.1 is the oldest version that has the fix.
Regards,
Attila
