### ISSUE TITLE
What's the best thread number for denoising

### ISSUE THREAD

**Issue by ColinChargyBentley** [OpenImageDenoise/oidn#105]
Hi,
If I set numThreads to 0, the doc said that it will be set automatically for best perf. Can we access this value ? We have another heavy process to run on the CPU (ie the render itself) and we would like the render to use the CPU thread the denoiser is not using.

Is the number of thread used by the denoiser depending on the the number of tiles ? If so, can we compute (or even better access) the number of tiles ?

Regards,
Colin Chargy
Bentley Systems

**Comment by atafra** [comment]
Hi Colin,

You can query the actual value of numThreads after commiting the device with oidnGetDevice1i. It's currently set to the number of physical cores and is independent of the number of tiles.

Regards,
Attila

**Comment by ColinChargyBentley** [comment]
Hi @atafra,
The information I would like to have is the number of thread that will be *really* used to denoise ? Is that the same as the number of tiles ? Can I get the number of tiles ?

Regards,
Colin Chargy
Bentley Systems

**Comment by atafra** [comment]
Hi Colin,

The value of numThreads that you can query *is* the actual number of threads that are used to denoise. It it *not* related to the number of tiles, and it is not possible to query the number of tiles. The tiles are denoised sequentially, each using the same number of threads (numThreads), so this number would not be useful anyway.

Regards,
Attila
