### ISSUE TITLE
New Intel TBB requirement breaks OpenVDB

### ISSUE THREAD

**Issue by Dade916** [OpenImageDenoise/oidn#109]
The new Intel TBB, required both by OIDN and Embree, breaks the compatibility with the past. In particular, it breaks OpenVDB compilation. As far as I know, OpenVDB (even the latest v8.x) compiles only with the old (pre-OneAPI ?) version.

This makes impossible to ship a single TBB version with the latest OIDN/Embree for anyone using OpenVDB: LuxCoreRender, Blender, etc.

P.S. I know this isn't strictly ODIN problem but TBB/ODIN/Embree/OpenVDB  should a bit coordinate their efforts to avoid this kind of problem because they are very likely to be used all together.

**Comment by atafra** [comment]
There might be a misunderstanding here. OIDN and Embree still does not require the new oneTBB, it's only the official binaries that use the latest oneTBB. It's difficult to pick a TBB version that is used by so many different libraries anyway, so the easiest solution is to rebuild these libraries with your preferred version of TBB. AFAIK this is what Blender and probably many other applications are doing.

**Comment by Dade916** [comment]
Ok, thanks. I can use two different TBB DLL versions on Linux, we are checking if it is possible on other OS. If we can't, we will compile Embree/ODIN from the sources as backup option.
