### ISSUE TITLE
Realtime denoising is possible?

### ISSUE THREAD

**Issue by darkoffalex** [OpenImageDenoise/oidn#111]
Is it possible to use OIDN for real-time path tracing? I tried, guided by the official documentation, but I did not succeed (https://youtu.be/Bc0AFGilpdM). The denoiser was running too slow for real time, and only on the CPU. Also, the denoised image was strange (everything looks like some kind of painting). Is this how it should be? Or did I do something wrong? I saw a demo on the internet (https://www.youtube.com/watch?v=N5ysfobkCjg), and the author said in the comments that he used OIDN. In this demo everything somehow worked in real time and the picture looked much better. How is this possible? Is it possible somehow to use OIDN in real time?

**Comment by atafra** [comment]
OIDN currently supports only CPUs, and it is possible to achieve interactive speeds (10+ FPS) but only on very powerful machines (50+ cores). Looking at that video, I think it's quite unlikely that it's really using OIDN.

**Comment by Calinou** [comment]
You could look into something such as https://github.com/BrutPitt/glslSmartDeNoise.
