### ISSUE TITLE
OIDN v1.4 : Is it already in Blender 2.92?

### ISSUE THREAD

**Issue by odil24** [OpenImageDenoise/oidn#115]
As topic by itself, so is it inside and already are we using? And another question is when we are rendering with OIDN in 3d view inaide Blender is it rendering or just shown option use OIDN for viewport but rendering with Optix (in my case if I use GPU compute)?

Thanks.

**Comment by atafra** [comment]
The is the repository of Open Image Denoise only. For integrations into applications please refer to the respective pages of those applications. Thanks!
