### ISSUE TITLE
Can't build on MAC - Apple Silicon

### ISSUE THREAD

**Issue by FlorentMasson** [OpenImageDenoise/oidn#117]
Error is:
```[ 2%] Building CXX object common/CMakeFiles/common.dir/platform.cpp.o
[ 4%] Building CXX object common/CMakeFiles/common.dir/tasking.cpp.o
[ 6%] Building CXX object common/CMakeFiles/common.dir/thread.cpp.o
[ 8%] Linking CXX static library ../libcommon.a
[ 8%] Built target common
[ 10%] Generating CXX source files from blob /Users/fiodortonti/documents/Denoiser/oidn/weights/rtlightmap_hdr.tza
[ 12%] Building ISPC object /Users/fiodortonti/documents/Denoiser/oidn/build/local__core/color.dev.o
Error: Unsupported value for --target-os, supported values are: macos 
make[2]: *** [local__core/color.dev.o] Error 255
make[1]: *** [CMakeFiles/OpenImageDenoise.dir/all] Error 2
make: *** [all] Error 2
```

Manually applying the fix listed in the [homebrew recipe](https://github.com/Homebrew/homebrew-core/blob/0ea72e51ab3b00ced38e6e3fd9c5b5acf4922324/Formula/open-image-denoise.rb#L25) made it work

**Comment by atafra** [comment]
It seems that Homebrew ships with an unofficial variant of ISPC, which cannot build OIDN correctly. The official ISPC builds, including the latest 1.16 work without any errors.

**Comment by FlorentMasson** [comment]
Does it feel right that [this line](https://github.com/OpenImageDenoise/oidn/blob/20dabd88217175021e2b5975320e843d4cef3cc1/cmake/oidn_ispc.cmake#L101) in oidn cmake is setting target to ios for arm64 and APPLE?
That's what the fix is removing

**Comment by atafra** [comment]
That line is necessary for official ISPC builds older than 1.6.0. `v1.4.1` fixes the compile error when using the latest ISPC that ships with Homebrew.
