### ISSUE TITLE
Blender denoising with multiple threads

### ISSUE THREAD

**Issue by gugugusheep** [OpenImageDenoise/oidn#118]
Hello.

If rendering in Blender on my CPU,   (64 virtual cores) the denoising phase gets annoyingly slow - just because it uses only one thread (instead it should use at least 16 in my case) to copute. 
Can you maybe fix this to be possible to set the number of used threads for denoising in future updates?

Thanks,
S.

**Comment by atafra** [comment]
Open Image Denoise already supports setting the number of threads. This sounds like a Blender issue, so this should be reported there instead.
