### ISSUE TITLE
Denoising a Realsense camera depth map?

### ISSUE THREAD

**Issue by alikendarfen** [OpenImageDenoise/oidn#119]
Hello,

I’m trying to find a way to enhance depth maps provided by Intel Realsense cameras (L515 or D435). The depth maps are often wavy on flat parts or spraying along edges and sometimes hard to use directly.

I was wondering if, by principle, using OpenImageDenoise can be a way to do that? Or is it structurally a dead end?

What are your advices?

Thanks for your reply.

**Comment by atafra** [comment]
Open Image Denoise is trained to denoise only rendered images, so it's not possible to denoise camera outputs. However, re-training it was such data might work, but you would need to do this yourself since this is beyond the scope of the library.
