### ISSUE TITLE
Is it possible to run on regular non filtered images?

### ISSUE THREAD

**Issue by fire** [OpenImageDenoise/oidn#12]
Is it possible to run on regular aliased images?

The idea is to provide an advantage on regular morphological AA and in ray tracing situations.

[Edited] regular morphological aa has the most problems with foilage.

[Edited] I wanted to investigate using this for Godot Engine as a dual use AA for both Raytracing and regular AA uses. Godot Engine currently doesn't have a raytracer engine, so there's no use using this unless it can also work for regular jagged images.

**Comment by atafra** [comment]
It should work with aliased ray traced images, but it won't anti-alias them. It can remove only Monte Carlo sampling noise.
