### ISSUE TITLE
Release tarballs of oidn-weights without data

### ISSUE THREAD

**Issue by jhgoebbert** [OpenImageDenoise/oidn#120]
Hello together,  
I just came across the release tarballs of oidn-weights and see that they are missing data.  
eg. https://github.com/OpenImageDenoise/oidn-weights/archive/refs/tags/v1.3.tar.gz

The binary files are git-lsf links, eg.:  
```
version https://git-lfs.github.com/spec/v1
oid sha256:e8d7ddb9843e99ea4bddb41e81d13bf4df876d19b81acd28e557589a9f9c351a
size 3659912
```

**Comment by atafra** [comment]
These are not actual releases, only tags. The tarballs are automatically generated by GitHub, and unfortunately it does not seem to be possible to remove them. The `oidn-weights` repository is a submodule of `oidn` and is not intended to be used separately, so please disregard these tarballs. The weights are correctly included in the official Open Image Denoise release tarballs (e.g. https://github.com/OpenImageDenoise/oidn/releases/download/v1.4.1/oidn-1.4.1.src.tar.gz)
