### ISSUE TITLE
GCC reports out of bounds array access warnings in xbyak.h 

### ISSUE THREAD

**Issue by DarkDefender** [OpenImageDenoise/oidn#123]
When building oidn with GCC on my machine I get quite a few warnings like this:
`mkl-dnn/src/cpu/x64/xbyak/xbyak.h:541:25: warning: array subscript 1 is outside array bounds of ‘Xbyak::Reg64 [1]’ [-Warray-bounds]`

Is GCC mistaken or does potential out of bounds array access happen?
I just wanted to report this in case this could be an issue.

**Comment by atafra** [comment]
This is a false alarm. It seems that only some very recent GCC versions believe that there is out of bounds array access here, but there isn't any.
