### ISSUE TITLE
Plans for half-float support?

### ISSUE THREAD

**Issue by TomCrypto** [OpenImageDenoise/oidn#13]
We use OIDN with a stream of inputs originally in half-float format (IEEE 754 half-float format, RGB/RGBA). Currently we convert the input images to 32-bit floats with SIMD intrinsics prior to denoising which works okay but does use extra memory and costs time; are there any plans to extend the RT filter to natively support half-float formats?

Thanks

**Comment by atafra** [comment]
We don't have any immediate plans to add half-float support but we'll consider it.
