### ISSUE TITLE
It's not clear how to run oidnDenoise

### ISSUE THREAD

**Issue by yurivict** [OpenImageDenoise/oidn#131]
Help screen isn't helpful (it doesn't even mention how to supply an image), and when run it always says:
```
Error: option expected
```

The error message should specify what option is meant.

**Comment by claudiomush** [comment]
Hello, I've the same problem: which option ?

**Comment by atafra** [comment]
Any option. It seems that the command was invoked with incorrect syntax but it's hard to say without knowing the exact command line.

The help screen **does** specify how to supply an image though (highlighted in **bold**):

> ./oidnDenoise -h
> Intel(R) Open Image Denoise
> usage: oidnDenoise [-d/--device default|cpu]
>                    [-f/--filter RT|RTLightmap]
>                    **[--hdr color.pfm] [--ldr color.pfm]** [--srgb] **[--dir directional.pfm]**
>                    **[--alb albedo.pfm] [--nrm normal.pfm]** [--clean_aux]
>                    [--is/--input_scale value]
>                    [-o/--output output.pfm] [-r/--ref reference_output.pfm]
>                    [-t/--type float|half]
>                    [-w/--weights weights.tza]
>                    [--threads n] [--affinity 0|1] [--maxmem MB] [--inplace]
>                    [--bench ntimes] [-v/--verbose 0-3]
>                    [-h/--help]

**Comment by yurivict** [comment]
@atafra 
Is there an example how to run oidnDenoise on a png image to produce a denoised png image?

**Comment by atafra** [comment]
`./oidnDenoise -ldr input.png -o output.png`
But you need to rebuild with OpenImageIO support to have PNG support.
