### ISSUE TITLE
Check supported output format before denoising

### ISSUE THREAD

**Issue by oxou** [OpenImageDenoise/oidn#132]
## Issue

`oidnDenoise.exe` starts the denoise process before ensuring the output format\
is supported by the compiled binary.

The command I used:
```
"C:\oidn\bin\oidnDenoise.exe"
    --device  cpu
    --alb     "C:\oidn\sample\0.pfm"
    --threads 4
    --maxmem  4096
    --output  "C:\oidn\output\0.png"
```

I mistakenly set the output file as `0.png` instead of `0.pfm` and waited for\
some time for the process to finish, until it said:

```
Error: cannot write unsupported image file format: 0.png
```

**Approximate time wasted**: 4 minutes and 13 seconds

## The fix

1. Check the output file extension
1.1 Terminate if conditions not met
3. Proceed to the denoise process

[comment]: <> (seo_track_id=91c7f37dae1b0148aaa52332012498d5fc5d95fdf93ab545330d11cfeca4315862d779517aa05848814fae35d2fb2c0a490bb061c4b7a4078e26cd6863cbc0bd)

**Comment by atafra** [comment]
I cannot reproduce this issue, the application immediately exits without any delay. The output file extension *is* checked and I don't see any reason why a delay might happen. Maybe you're using some anti-malware software which could cause such an issue.

**Comment by atafra** [comment]
`oidnDenoise` is not meant to be used as a full-featured denoising application but it's only a tutorial for developers. A 4 minute denoising time is rather unusual (it's typically not more than a second or two) so we haven't encountered this issue before. Adding an early file extension check is currently not planned but we welcome any pull requests that would do this.
