### ISSUE TITLE
Question: API used for upcoming OIDN GPU support?

### ISSUE THREAD

**Issue by oscarbg** [OpenImageDenoise/oidn#136]
Hi,
seems Intel has presented a Blender denoising GPU plugin supporting multiple vendors like NV and AMD..
assuming it's coming as part of OIDN GPU support, just asking what compute API supports: OpenCL? via Vulkan compute?
also will support Macos via Metal?

thanks..

**Comment by atafra** [comment]
Hi. OIDN will initially support SYCL, CUDA and HIP.

**Comment by oscarbg** [comment]
thanks!

**Comment by oscarbg** [comment]
any update on this? basically some rough ETA on availability?
thanks..
