### ISSUE TITLE
Clarification on the normal buffer

### ISSUE THREAD

**Issue by TomCrypto** [OpenImageDenoise/oidn#14]
This doesn't seem to be specified anywhere, but should the contents of the normal buffer be literal normals with potentially negative values, or should they be converted to positive values using N * 0.5 + 0.5? The bit about arbitrary lengths being allowed suggests the former and it does seem to work fine, but I just wanted to have hard confirmation. It's not completely obvious to me since the other buffer contents are always strictly nonnegative so maybe it's worth a mention in the readme either way?

**Comment by atafra** [comment]
The normals should be the actual normal vectors, with both positive and negative values. We've updated the documentation to clarify this.
