### ISSUE TITLE
Building for Windows on ARM

### ISSUE THREAD

**Issue by steplong** [OpenImageDenoise/oidn#143]
I'm trying to building for Windows on ARM, but it looks like mkl-dnn is built for x64. How were the sources chosen in oidn/cmake/oidn_dnnl.cmake? It looks like there are more sources in mkl_dnn/src/cpu/x64. I also modified CMakeLists.txt:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 96ca5d1..583eeb6 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -85,6 +85,8 @@ if(OIDN_ARCH STREQUAL "X64")
 endif()
 if(APPLE AND OIDN_ARCH STREQUAL "ARM64")
   list(APPEND OIDN_NEURAL_RUNTIMES "BNNS")
+elseif(OIDN_ARCH STREQUAL "ARM64")
+  list(APPEND OIDN_NEURAL_RUNTIMES "DNNL")
```

**Comment by atafra** [comment]
Sorry, OIDN does not have generic ARM support yet, only Apple Silicon. It's not possible to compile for Windows/Linux on ARM.

**Comment by steplong** [comment]
Hi, what would be needed to add generic ARM support?

**Comment by atafra** [comment]
It would be a complex task. It's on our roadmap but we're currently focusing on implementing GPU support.

**Comment by StefanBruens** [comment]
Can you please reopen this one? It is not actually completed, but having it in "Closed" state makes it harder to find.

Maybe you can also improve the README.md - it mentions oneDNN, but that does not (no longer) exclude other architectures, and Apple Silicon apparently does not use oneDNN.
