### ISSUE TITLE
Denoise Result 

### ISSUE THREAD

**Issue by lgdu** [OpenImageDenoise/oidn#148]
Hello,
I ran  oidnDenoise to proceess mazda_4spp_input.jpg,but the result is not good as mazda_4spp_oidn.jpg in https://www.openimagedenoise.org/documentation.html
Could you please provide a correct command line to get the same result as that in your website? 
Thanks

**Comment by atafra** [comment]
Hi. Lossily compressed images should not be used. Lossy compression destroys information which makes denoising fail.
