### ISSUE TITLE
Support big-endian PFM images

### ISSUE THREAD

**Issue by Peregrine05** [OpenImageDenoise/oidn#149]
Currently, attempting to load a big-endian PFM image results in the following error:
```
Error: big-endian PFM images are not supported
```

**Comment by Calinou** [comment]
> We're not planning to support this by default but it should work if you build with OpenImageIO support

Could OpenImageIO be enabled in official binary releases? This would smoothen out the workflow a lot when using on OpenEXR images.

**Comment by atafra** [comment]
No, sorry. The included applications were not intended to be used in production, these are just samples.
