### ISSUE TITLE
[CRITICAL] Where is the maintained original oidn repository

### ISSUE THREAD

**Issue by ghost** [OpenImageDenoise/oidn#156]
This repository has no commit activity since over a year.

I am assuming that

* oidn is not maintained anymore
* there is another repository where development happens

Please clarify this (ideally prominently within e.g. the README, so users can see/know it immediately)

**Comment by atafra** [comment]
Open Image Denoise 2.0 has been already announced publicly and will be released soon.

**Comment by abebeos** [comment]
Is it an internal repo? I cannot find anything.

**Comment by atafra** [comment]
It is an internal repo.

**Comment by abebeos** [comment]
> It is an internal repo.

You should clarify this in the readme.

Otherwise it looks really abandoned.

So, one cannot contribute/influence the development.

Are you aware if 2.0 has bazel support (at least an external one, in the form of a repo rules_oidn)?

**Comment by atafra** [comment]
2.0 won't ship with Bazel support. That's all I know for sure.

**Comment by abebeos** [comment]
Ok, ty for the info.

Please ensure to add a readme note re ongoing internal 2.0 work.

And consider to change your dev-model to an open one in future.

**Comment by abebeos** [comment]
@atafra , will 2.0 support mac M1?

(is there any announcement re the functionality of the 2.0 version? would be nice. A public Release Candidate would be of course even better)

**Comment by Vertexwahn** [comment]
@atafra Since oidn 1.4.3 works also on macOS M1 + there is this nice PR -> https://github.com/OpenImageDenoise/oidn/pull/138 I I expect good support for macOS M1
