### ISSUE TITLE
Questions about 2.0 release: request for lowered GPU requeriments for both 3 vendors, MacOS GPU support..

### ISSUE THREAD

**Issue by oscarbg** [OpenImageDenoise/oidn#160]
Hi,

first, thanks for a nice release..

still asking if GPU requirements can be lowered somehow..

I have and "old PC" with 3 GPUs from Intel AMD and Nvidia:

*Intel Skylake i5 with HD 530(Gen9 iGPU)
*AMD RX Vega (gfx900)
*Nvidia Maxwell (sm_52)

and seems neither is supported..

any specific reason to limit to Intel Xe+ (>=gen12), RDNA2+ (>=gfx1030) and Volta+ (>=sm_70)..

finally asking if there are plans for Apple GPU support (i.e. merging Apple MPS pull request (https://github.com/OpenImageDenoise/oidn/pull/138)) in next release (so 2.1? release)

thanks..

**Comment by atafra** [comment]
Hi,

Sorry, we cannot lower the GPU requirements but OIDN 2.0 can still run on the CPU on such machines with full functionality.

Apple GPU support is planned soon but not by merging #138 because it needs to be almost completely rewritten.

**Comment by YAFU** [comment]
> Hi,
> 
> Sorry, we cannot lower the GPU requirements but OIDN 2.0 can still run on the CPU on such machines with full functionality.
> 
> Apple GPU support is planned soon but not by merging #138 because it needs to be almost completely rewritten.

Hi.
Not including nVidia Maxwell architecture is it because of some limitation?

nVidia OptiX works seamlessly on Maxwell cards.

**Comment by atafra** [comment]
Hi. OIDN is using NVIDIA CUTLASS, which dropped support for Maxwell and even Pascal. OptiX is a completely different product so it's not directly comparable.

**Comment by YAFU** [comment]
OK, sad because I won't be able to use OIDN with acceleration on my GPU. But anyway, thanks for your excellent work.
