### ISSUE TITLE
Determine which instruction set is being used

### ISSUE THREAD

**Issue by hueyline** [OpenImageDenoise/oidn#171]
- How can I determine which instruction set is being used by OpenImageDenoise when the CPU supports multiple instruction sets (SSE, AVX2, AVX512)? 
- Can I dynamically change the instruction set that is being used?

**Comment by atafra** [comment]
It's not possible to query the instruction set used or to change it. Why would you need to do these?

**Comment by hueyline** [comment]
Just would like to explore the denoising performance with different instruction sets (e.g. AVX512 vs AMX), in order to determine the extent of the performance boost provided by more advanced instruction sets.

**Comment by atafra** [comment]
OIDN currently does not (and cannot) support AMX. OIDN always uses the latest available instruction set. For benchmarking I suggest to use oneDNN directly, which OIDN is using on the CPU.

**Comment by hueyline** [comment]
I see. I would like to learn from you. As I understand it, the ray tracing filter is based on CNN models. Theoretically, if OIDN supports AMX, the denoising performance should be improved, right?

**Comment by atafra** [comment]
Yes, if AMX would support FP16, OIDN could use it, and performance would be better.
