### ISSUE TITLE
Precompiled binaries for apple arm64

### ISSUE THREAD

**Issue by thomasloockx** [OpenImageDenoise/oidn#175]
Hi, 

I'm trying to use the OIDN pre-built binaries from the official website: https://www.openimagedenoise.org/downloads.html - But I see that there are only Apple binaries available for `x86_64`, not for the `arm64` architecture. This results in a problem when linking:
```
ld: warning: ignoring file /Users/tloockx/dev/Rayscaper/src/cpp/third-party/oidn-2.0.1.x86_64.macos/lib/libOpenImageDenoise.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
```

Is it possible to provide precompiled binaries for Apple silicon?

**Comment by atafra** [comment]
Yes, we're planning to provide `arm64` binaries for our future releases. Meanwhile please try to build OIDN from source.

**Comment by atafra** [comment]
Starting with `v2.2.0` we're now shipping ARM64 binaries for macOS: https://github.com/OpenImageDenoise/oidn/releases/tag/v2.2.0
