### ISSUE TITLE
Lost negative value of directional lightmap

### ISSUE THREAD

**Issue by lvjiahui** [OpenImageDenoise/oidn#191]
Hi,
When using RTLightmap filter, It is said in the document that the input directional values are in [-1, 1]. But I find all negative value is clamped to 0 in the output.
If I map the input value to [0, 1], and map the output back to [-1,1], it seems to work correctly.
So I'm wondering if I'm doing something wrong or the documentation has a mistake?
Thanks!

**Comment by atafra** [comment]
Did you set the `directional` filter parameter to `true`? The input is expected to be in [-1, 1] only if this is set, as described in the documentation.

**Comment by lvjiahui** [comment]
It turns out that my input data is slightly out of [-1,1] range. After I clamp the input data everything is ok!
