### ISSUE TITLE
Windows release has erronous link paths specified in the CMake config

### ISSUE THREAD

**Issue by skurmedel** [OpenImageDenoise/oidn#2]
Row 56 in the file OpenImageDenoiseConfig.cmake of the latest release (0.8) has this line:

`INTERFACE_LINK_LIBRARIES "C:/<build machine path>/lib/intel64/vc14/tbb.lib;C:/<build machine path>/lib/intel64/vc14/tbbmalloc.lib"`

Where `<build machine path>` seems to be local to the release machine. Naturally, this path does not exist on my machine :) Setting it to:

`INTERFACE_LINK_LIBRARIES "${_IMPORT_PREFIX}/lib/tbb.lib;${_IMPORT_PREFIX}/lib/tbbmalloc.lib"` 

fixes compilation issues.

**Comment by atafra** [comment]
Fixed it in `devel`, will be released in `v0.8.1` soon. Thanks!
