### ISSUE TITLE
need explanation parameter denoise.exe -ref reference_output.pfm

### ISSUE THREAD

**Issue by comsyspro** [OpenImageDenoise/oidn#25]
1. I'm testing denoise.exe v0.8.2 on a windows platform and want to know what the parameter 

> -ref reference_output.pfm

 in the command line stands for. Please can someone explain?

2. Are there any additional parameters for denoise.exe in which you can setup some values for the noise reduction filter settings like strength etc...?

**Comment by jomeng** [comment]
If you provide a reference image, then the denoise application will compare the denoised output with the reference image, compute an error metric and store a difference image. This is useful to evaluate the quality of the denoiser.

Please note that the denoise application is merely an example to show how Open Image Denoise can be used. 

The denoiser does expose a strength setting.
