### ISSUE TITLE
denoised LDR image returns greater than 1.0 values

### ISSUE THREAD

**Issue by Woking-34** [OpenImageDenoise/oidn#26]
Hi,

I give the sample denoise app a pfm file in [0,1] range and it seems oidn returns greater than 1.0 values in the result buffer, is this an expected behavior?

My cmd args: -ldr rtow.pfm -o ouput.pfm

Thanks!

**Comment by atafra** [comment]
This happens due to how the filter works, but we'll clamp the output to [0, 1] to fix this issue. Thanks!

**Comment by atafra** [comment]
Fixed in the `devel` branch.
