### ISSUE TITLE
Denoising image won't denoise whole image

### ISSUE THREAD

**Issue by rodrigobriet** [OpenImageDenoise/oidn#29]
I am trying to denoise a rendered image from VRay with the OIDN, but the noise is removed only on some regions on the image, as show on the image bellow (click to enlarge).

![image](https://user-images.githubusercontent.com/7749707/57680956-22aa2200-7605-11e9-9c4e-c817be1f91cf.png)

The original image (a .png) is converted to .pfm with magick using this command:
`magick convert -endian LSB PATH_IN PATH_OUT`

And i am running the denoise with the following command:
`denoise.exe -ldr PATH -alb PATH -nrm PATH -o PATH`

Do someone have some tip for why this is happening? Can it be some incompatibility from my type of image with what OIDN can work it?

If someone want to test it, [here is the original files](https://drive.google.com/uc?export=download&id=1q9rlUuvEMD9ZZ8WQJKiSmhQ3pwmVb8eg).

**Comment by atafra** [comment]
It's hard to say by just looking at the images, but it looks like the pixel filter is applied by splatting, which is not supported by the denoiser. Only filter importance sampling is supported by Open Image Denoise.
