### ISSUE TITLE
No noticeable improvement with denoise.exe

### ISSUE THREAD

**Issue by ted-kapustin** [OpenImageDenoise/oidn#30]
I tried using denoise.exe with raytraced images that I generated with Blender. I tried it with images generated using 64, 32, 16, 8, 4, 2, and 1 samples per pixel. There was no noticeable improvement of the image's quality. Moreover, the source and output images look identical (they both have "salt and pepper" look). However, when I use ImageMagick's compare utility, it shows some subtle differences. I generated 24-bpp (8 bits per channel) sample images (I saved them in BMP format) from Classroom sample scene available on Blender Web site. I then converted BMP files to PFM using my own program, then used them as input files with -ldr option, and then converted output images to BMP using my other program. All images have 3840x2160 dimensions.

Am I doing something wrong, or maybe something is wrong with the program?

I am on 64-bit Windows 10. I can share the code of my program that converts BMP to PFM if necessary.

**Comment by atafra** [comment]
Open Image Denoise works only with images which have no post-processing applied (e.g. distortions). AFAIK the Blender Classroom scene does have some kind of post-processing, which causes the denoising to fail. The post-processing needs to be applied after denoising. This is why denoising ideally should be integrated into a renderer, and not used separately. The included example (`denoise`) was not intended to be used as an end-user application. It's only a tutorial for developers who would like to integrate the denoiser into a renderer.

**Comment by gonsolo** [comment]
I have the same problem; the denoised image looks just like the original. Please have a look at the original and denoised image. The original image is unprocessed output from a path tracer and converted with imagemagick via "convert -endian LSB bathroom.exr bathroom.pfm" and denoised with "denoise -hdr bathroom.pfm -o denoised.pfm"
[bathroom.zip](https://github.com/OpenImageDenoise/oidn/files/3241382/bathroom.zip)
