### ISSUE TITLE
Sample based denoising 

### ISSUE THREAD

**Issue by gonsolo** [OpenImageDenoise/oidn#31]
Hi. 

Are you considering denoising directly from samples? It’s unfortunate that so much information is thrown away, e.g. when rendering with 16spp I would expect much better results from 16 samples than from one pixel value.

**Comment by atafra** [comment]
Hi! No, currently we don’t have any plans to implement such a denoising algorithm. The state-of-the-art AI denoising approaches all use only the average pixel values, and that’s what we are currently doing. If perhaps you know about a published algorithm that performs better using all the samples, we would be happy to have a look. Thanks!

**Comment by a-wendleder** [comment]
FYI: https://groups.csail.mit.edu/graphics/rendernet/

**Comment by gonsolo** [comment]
FYI: https://groups.csail.mit.edu/graphics/rendernet/
