### ISSUE TITLE
Oidn fails on very light shadows

### ISSUE THREAD

**Issue by Dade916** [OpenImageDenoise/oidn#33]
We have received some report of Oidn failing to denoise image area with very light shadow. It is like if there is a threshold under which noise is not removed.

This is an example of the problem, the normal rendering:

![normal](https://user-images.githubusercontent.com/3247881/59032368-655ac500-8866-11e9-950e-0ba08928bf27.png)

and the is the Oidn output:

![denoised](https://user-images.githubusercontent.com/3247881/59032367-64c22e80-8866-11e9-9aed-cef34cd8e04e.png)

The very end of the monkey shadow is not denoised, there is a quite sharp cutoff.

This is a .zip with the .png/.exr rendering images, albedo and normal AOVs to replicate the problem:

[img.zip](https://github.com/OpenImageDenoise/oidn/files/3261496/img.zip)

This is the thread in our forum where the problem is discussed: https://forums.luxcorerender.org/viewtopic.php?f=4&t=1122

From the above forum thread, another example of the problem in a real world scene can be seen here: https://forums.luxcorerender.org/viewtopic.php?f=4&t=1122&start=10#p13302

**Comment by atafra** [comment]
Thanks for reporting this issue! We are currently preparing a new release, which will fix this. This is the produced output with the new version (not final yet):

![denoised_new2](https://user-images.githubusercontent.com/4058111/59038995-a3fb7a00-887c-11e9-92ae-48e3ca0325a0.png)

**Comment by Dade916** [comment]
Thanks Attila, I guess we can close this.
