### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by shadowzoom** [OpenImageDenoise/oidn#34]
Hi there! How i can use it? Also would be awesome if someone can be create image for Colab notebook like in https://github.com/jantic/DeOldify
How i can denoise single jpg? Please write me steps what i need to do, i'm very need to denoise some of my family images, my father is dying by cancer and i wanna surprise him with this. Thanks!

**Comment by jomeng** [comment]
I'm afraid Open Image Denoise may not be what you are looking for. We use a machine learning algorithm that is trained specifically for the output of Monte Carlo rendering systems. It would probably have difficulties restoring old photographs in its current state.
