### ISSUE TITLE
Build error on Mac

### ISSUE THREAD

**Issue by Ono-Sendai** [OpenImageDenoise/oidn#35]
Hi,
We're trying to build oidn 0.9.0 on Mac, and are hitting this error:

    Building CXX object mkl-dnn/src/CMakeFiles/mkldnn.dir/common/batch_normalization.cpp.o
    clang: error: unknown argument: '-fopenmp-simd'

clang -v gives

    Apple LLVM version 9.1.0 (clang-902.0.29.2)

The mac is running macOS High Sierra Version 10.13.6.

**Comment by jomeng** [comment]
This problem is fixed in recent versions of Apple LLVM. Do you have the option of upgrading?

**Comment by Ono-Sendai** [comment]
This indeed doesn't seem to be a problem on macOS Catalina, so closing.
