### ISSUE TITLE
Is there any chance to make this work with animations?

### ISSUE THREAD

**Issue by FrankEscobar** [OpenImageDenoise/oidn#36]
Or there will be?

OID works really nice but makes some flickerings on animation so my question is this will be temporal coherent in the future?

Regards.

**Comment by atafra** [comment]
Yes, temporal coherence is planned for a future release.

**Comment by FrankEscobar** [comment]
You make me so happy ;-)

**Comment by enyo** [comment]
@atafra is there any estimation on when this could be ready to go?

**Comment by atafra** [comment]
Sorry, we don't have an estimate yet.

**Comment by ChristopheMoreau** [comment]
> Sorry, we don't have an estimate yet.

Hi, and what about now ? :)

**Comment by atafra** [comment]
What I can disclose at this time is that the upcoming major release will add GPU support, and temporal coherence will be next.

**Comment by oinotna** [comment]
Hi, what about now?

**Comment by chrisbrejon** [comment]
Hello @atafra we were wondering if there had been any progress on temporal coherence ? Thanks a lot !

**Comment by Howard-Day** [comment]
Any news on this? :)

**Comment by chrisbrejon** [comment]
@Howard-Day Something might be released by the end of the year regarding temporal stability.
