### ISSUE TITLE
GPU support?

### ISSUE THREAD

**Issue by ivalylo** [OpenImageDenoise/oidn#37]
Are there plans for Intel GPU support? MKL-DNN seems to be progressing in that direction, so I guess OIDN will also pick on that?

**Comment by atafra** [comment]
Yes, GPU support is planned for a future release.

**Comment by ValZapod** [comment]
@atafra What about Nvidia Tensor cores? I can imagine this being an AI denoiser will benifit tremendously. For example, with leela chess network training is like 12-20 times faster with new cores in turing. That was just crazy. Just see all --backend=cudnn-fp16 in here https://docs.google.com/spreadsheets/d/1lGFf6PLGmBUSMan-YP7Vul4DpRNfn6K8oeCjBILe6uA/htmlview#gid=0

**Comment by ColinChargyBentley** [comment]
Hi @atafra ,
We've well noticed that GPU support is planned for a future release and we can't wait!
In the meantime, I was wondering if there are incompatibilities between oneDNN compiled with GPU support and OIDN (which are they?) or you've simply did not test this (and don't want to support it for now) ? Could you elaborate on technical challenges to overcome or change needed to allow OIDN to use GPU ?

Thank you for your answer,
Regards,
Colin Chargy

**Comment by atafra** [comment]
Hi Colin! Adding GPU support has many challenges. First, we're using a custom fork of oneDNN, so we need to port our changes to the GPU implementation as well, which is non-trivial. Also, the denoising filters have stages which cannot be performed with oneDNN and so are implemented with custom code, which also needs to be ported to the GPU.

**Comment by ColinChargyBentley** [comment]
Hi @atafra ,
Thanks for your answer.
Regarding the filters stages, could we imagine have everything else done on the GPU and filters done on CPU (with the current custom code) ? Do you imagine this approach would give good results ?

Regards,
Colin Chargy

**Comment by atafra** [comment]
No, I don't think a mixed approach would give good enough results.

**Comment by ColinChargyBentley** [comment]
That made perfect sense, thank you!

**Comment by ahcox** [comment]
Is GPU support still in progress?

**Comment by atafra** [comment]
Yes, it is: https://twitter.com/IntelTech/status/1435698381268025347?s=20

**Comment by ColinChargy** [comment]
Is it limited to Intel GPUs ?

**Comment by atafra** [comment]
Currently we're focusing on Intel GPUs.
