### ISSUE TITLE
Mailing list question

### ISSUE THREAD

**Issue by zomgrolf** [OpenImageDenoise/oidn#39]
I tried to join the mailing list (as per 'Support and Contact' section in the README), but Google says I don't have permission to access the content. I tried emailing openimagedenoise@googlegroups.com, but it bounced. Is it actually open to public?

**Comment by atafra** [comment]
Yes, the mailing list is open to public, but you have to join first. Please try joining again.

**Comment by zomgrolf** [comment]
I tried following the link in the README again to join the group, but I was still getting the following error: 
 "You do not have permission to access this content. (#418)"
I also tried searching for openimagedenoise from the main page of Google Groups, but without success. I tried searching for that specific error message and this is one of the first links I got:
[Accepting invite to google group didn't work, group won't show up](https://support.google.com/a/thread/5541512?hl=en).
Perhaps it's related?

**Comment by robp-mpc** [comment]
Same issue ... unable to get enough access to the group/mailing-list to actually join it.

**Comment by atafra** [comment]
Sorry, please try again: https://groups.google.com/d/forum/openimagedenoise

**Comment by zomgrolf** [comment]
Yep, works for me now, thanks.
