### ISSUE TITLE
Only physical cores are used on Threadripper

### ISSUE THREAD

**Issue by arthur-liebnau** [OpenImageDenoise/oidn#41]
Hey I just noticed that OIDN seems only to use the physical cores of my Threadripper and not all of the logical cores the system has to offer.
Any chance to utilize the full power of such systems?
![cores](https://user-images.githubusercontent.com/56542366/66746675-c0d73800-ee82-11e9-9aaa-62643444ac25.png)

**Comment by atafra** [comment]
Hi! This happens on any CPU not just Threadripper, and it's intentional. Running on all threads is actually slower with this workload, so the current approach is the highest performing one.

**Comment by arthur-liebnau** [comment]
thanks for the quick reply! Keep on rockin' :)
