### ISSUE TITLE
Error generating project

### ISSUE THREAD

**Issue by mesajflaviu** [OpenImageDenoise/oidn#44]
When I tried to generate the solution project, with CMake 3.13.4 (64bit), and select VS2017, I got these CMake errors (message):
```

Selecting Windows SDK version 10.0.17134.0 to target Windows 10.0.17763.
CMake Error at CMakeLists.txt:88 (add_subdirectory):

  The source directory

    D:/Project/oidn/mkl-dnn

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:91 (include):
  include could not find load file:

    mkl-dnn/cmake/Threading.cmake


CMake Error at CMakeLists.txt:92 (include):
  include could not find load file:

    mkl-dnn/cmake/TBB.cmake


CMake Error at CMakeLists.txt:93 (include):
  include could not find load file:

    mkl-dnn/cmake/platform.cmake


CMake Error at CMakeLists.txt:94 (include):
  include could not find load file:

    mkl-dnn/cmake/SDL.cmake


CMake Error at CMakeLists.txt:97 (append):
  Unknown CMake command "append".


Configuring incomplete, errors occurred!
See also "D:/Project/oidn/bin/CMakeFiles/CMakeOutput.log".
```

What else should I do in order to generate a solution for this library ?

**Comment by atafra** [comment]
Did you checkout the source from GitHub? If you did, did you checkout the subrepositories too? It looks like the mkl-dnn directory empty, which is one of the submodules.

**Comment by mesajflaviu** [comment]
Yes, mkl-dnn folder is empty, and I simply download the github project from browser, and not using github tool. Meanwhile, I noticed that I got the compiled windows project, and for me is enough.
