### ISSUE TITLE
Support for grayscale pfm images.

### ISSUE THREAD

**Issue by gonsolo** [OpenImageDenoise/oidn#45]
Imagemagicks's convert automatically converts my EXR albedo images to grayscale PFM files (with an Pf header for grayscale instead of PF for color image) and denoise is refusing this type of image. Please add support for that.

**Comment by atafra** [comment]
This might be a bug in ImageMagick. Albedo images have 3 channels, so the converted PFM files also need to have 3 channels. Grayscale albedo images are invalid thus cannot be supported.

**Comment by gonsolo** [comment]
I filed a bug for imagemagick too. But I think the denoiser would be a bit more friendlier to users to accept that file since without hexdumping the pfm file it looks like the denoiser is randomly failing.

**Comment by atafra** [comment]
Albedo *must* be 3 channels, so it cannot accept a grayscale image. Also, Open Image Denoise is a library, not a standalone application. The included command line application is just an example for developers and is not intended to be a feature-complete denoising application.

**Comment by gonsolo** [comment]
I received a bug fix from an Imagemagick developer within the hour (which doesn't fix my issue but we're getting there :) ); https://github.com/ImageMagick/ImageMagick/issues/1783, so my problem is or will be eventually be solved.

I *still* think, from a usability point of view it still would be nice to just swallow the file and convert internally to 3 channels (not even mentioning spectral renderers ;) ).

Thanks anyway for your explanation.
