### ISSUE TITLE
More information/transparency on how OIDN was trained?

### ISSUE THREAD

**Issue by jessey-git** [OpenImageDenoise/oidn#51]
Not a bug, just a curiosity.  Would it be possible to go into a bit more detail about how training data has been created for training OIDN?  Something like the following which could be posted on the main website?

- Scenes
   - OIDN 1.2: We used 110 different scenes, native to 3 different Path Tracing engines, to train our model: 40 from OSPRay, 50 from Arnold, 20 from Cycles 
    - OIDN 1.0: We used 80 different scenes, native to 2 different Path Tracing engines, to train our model: 40 from OSPRay, 40 from Arnold
- Ground Truth setup
    - We use 10000 samples as the ground-truth measurement for each scene
- Test images
    - We use a wide range of samples per pixel (spp) values, from 1 to almost fully converged, to generate the test corpus
    - To be exact, the following 15 spp values are used for each scene to generate training data:
		1, 2, 4, 10, 25, 50, 100, 200, 400, 500, 1000, 2000, 4000, 6000, 8000

To be clear, I'm not asking that the actual assets or images be posted etc. Just a more in depth, broad outline, of methodology with a version history perhaps?

**Comment by jomeng** [comment]
Thank you for your request. However, I'm afraid that we are not ready to share this information at this point.
