### ISSUE TITLE
Denoise 1 frame using multiple frames

### ISSUE THREAD

**Issue by DEBIHOOD** [OpenImageDenoise/oidn#52]
Add “noise flicker removal feature"
As far as I know it first appeared in Disney’s own denoiser.  I don’t quite know how it works, but it’s something like denoiser is analyzing next frames, and trying to avoid noise jitter, this is very useful for animations. This function is in standart blender cycles denoiser, but it is not in the interface, it seems to be used through python or smth, but I don’t know how, if you make this, I think you can use it as a source.
https://developer.blender.org/D3889

**Comment by jomeng** [comment]
Thank you for your request! Support for animations is on our radar, but it's hard to tell when that will be available.
