### ISSUE TITLE
Pointer to const type for input images

### ISSUE THREAD

**Issue by tomilov** [OpenImageDenoise/oidn#54]
Set proper `const void *` instead of `void *` for **read-only** input data [here](https://github.com/OpenImageDenoise/oidn/blob/0fffd8422833a3e01170dab31a10341a741b04df/include/OpenImageDenoise/oidn.hpp#L219).

**Comment by atafra** [comment]
Images are not necessarily read-only input data. Output images are also set with this function.

**Comment by tomilov** [comment]
@atafra it is not an excuse for a violation of const-correctness. I suggest to add `const void *` overloading.
Currently there is the only workaround: to use `const_cast`. Just because the API is poor in this place.
