### ISSUE TITLE
oidn only work on learned image ? poor effect on my test

### ISSUE THREAD

**Issue by lion117** [OpenImageDenoise/oidn#55]
hi , guys , I used **OpenImageDenoise.exe**  do some test . but the result was very sad.  

here is the compare effect 

#  house
![](https://cdmd-1257623782.cos.ap-chengdu.myqcloud.com/mdpic/20200207152206.png)

# car
![](https://cdmd-1257623782.cos.ap-chengdu.myqcloud.com/mdpic/20200207152230.png)

# randon noise
![](https://cdmd-1257623782.cos.ap-chengdu.myqcloud.com/mdpic/20200207152255.png)

# stars
![](https://cdmd-1257623782.cos.ap-chengdu.myqcloud.com/mdpic/20200207152308.png)

![](https://cdmd-1257623782.cos.ap-chengdu.myqcloud.com/mdpic/20200207153813.png)

![](https://cdmd-1257623782.cos.ap-chengdu.myqcloud.com/mdpic/20200207161050.png)

![](https://cdmd-1257623782.cos.ap-chengdu.myqcloud.com/mdpic/20200207161132.png)

## Is this a kpi guiding project ?  
1. test effect is realy poor. 
2. image input  and output format require PFM , which is really awful   for Engineering. why not wrap the APIS

**Comment by jomeng** [comment]
Hi,

I think there may have been a problem during image upload. Can you re-upload so we can see the full images?

Can you also describe in more detail what it is exactly that you find objectionable? That way we can hopefully respond better.

As for PFM - the denoise program is just a demo application. The Open Image Denoise API does not
require PFM. 
If you need other image formats for evaluation, you can either convert the image format of your choice to PFM and then run denoise, or you could also change the denoise program to support that format directly.

**Comment by lion117** [comment]
I had uploaded those images into my cloud storage bukcet. download directly 
#  [house](https://cdmd-1257623782.cos.ap-chengdu.myqcloud.com/mdpic/20200207152206.png)


# [car](https://cdmd-1257623782.cos.ap-chengdu.myqcloud.com/mdpic/20200207152230.png)


## [randon noise](https://cdmd-1257623782.cos.ap-chengdu.myqcloud.com/mdpic/20200207152255.png)


## [stars](https://cdmd-1257623782.cos.ap-chengdu.myqcloud.com/mdpic/20200207152308.png)


## [beauty](https://cdmd-1257623782.cos.ap-chengdu.myqcloud.com/mdpic/20200207153813.png)


## [face_boy](https://cdmd-1257623782.cos.ap-chengdu.myqcloud.com/mdpic/20200207161050.png)


## [face_girl](https://cdmd-1257623782.cos.ap-chengdu.myqcloud.com/mdpic/20200207161132.png)

**Comment by arthur-liebnau** [comment]
OIDN not designed and trained for video or photo footage!

The first sentence in the OIDN description:

> Intel Open Image Denoise is an open source library of high-performance, high-quality denoising filters for images rendered with ray tracing

**Comment by jomeng** [comment]
@lion117 Thank you for the update!

It is correct that Open Image Denoise is designed for the output of Monte Carlo rendering systems. 
We do not support photographs as input. So that means that the "face_boy" and "face_girl" photographs are simply not the intended use case.

However, you also posted rendered examples (e.g. the "car" image). Can you describe in more detail in what way the denoised output of those rendered images does not meet your expectations?
