### ISSUE TITLE
Denoise .pfm file, Error: invalid tensor format

### ISSUE THREAD

**Issue by Zhenyi-Liu** [OpenImageDenoise/oidn#59]
Hi,

I got the error as described in the title when I deonise a .pfm, same for ldr and hdr case.
I am using the version 1.2.0, no errors when I used 1.1.0.
Thanks.

**Comment by atafra** [comment]
Hi,

Did you use an official binary or did you build the library yourself? If you built it yourself, did you download an official source package or did you check out the Git repository? What operating system are you using?

Thanks,
Attila

**Comment by Zhenyi-Liu** [comment]
> Hi,
> 
> Did you use an official binary or did you build the library yourself? If you built it yourself, did you download an official source package or did you check out the Git repository? What operating system are you using?
> 
> Thanks,
> Attila

Hi, I tried the official binary, it worked, so I think it was my mistake, thanks! I think I will just use the binary.
