### ISSUE TITLE
Internal compiler Error with gcc 8.2.1 stable branch on Linux

### ISSUE THREAD

**Issue by seanvk** [OpenImageDenoise/oidn#6]
seanvk@clr-eugene-svkelley ~/dev/oidn/build $ gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-generic-linux/8.2.1/lto-wrapper
Target: x86_64-generic-linux
Configured with: ../gcc-8.2.0/configure --prefix=/usr --with-pkgversion='Clear Linux OS for Intel Architecture' --libdir=/usr/lib64 --enable-libstdcxx-pch --libexecdir=/usr/lib64 --with-system-zlib --enable-shared --enable-gnu-indirect-function --disable-vtable-verify --enable-threads=posix --enable-__cxa_atexit --enable-plugin --enable-ld=default --enable-clocale=gnu --disable-multiarch --enable-multilib --enable-lto --enable-linker-build-id --build=x86_64-generic-linux --target=x86_64-generic-linux --enable-languages=c,c++,fortran,go --enable-bootstrap --with-ppl=yes --with-isl --includedir=/usr/include --with-gxx-include-dir=/usr/include/c++/ --exec-prefix=/usr --with-glibc-version=2.19 --disable-libunwind-exceptions --with-gnu-ld --with-tune=haswell --with-arch=westmere --disable-libmpx
Thread model: posix
gcc version 8.2.1  (Clear Linux OS for Intel Architecture) 

seanvk@clr-eugene-svkelley ~/dev/oidn/build $ cmake ..
-- The CXX compiler identification is GNU 8.2.1
-- Check for working CXX compiler: /usr/lib64/ccache/bin/g++
-- Check for working CXX compiler: /usr/lib64/ccache/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The C compiler identification is GNU 8.2.1
-- Check for working C compiler: /usr/lib64/ccache/bin/gcc
-- Check for working C compiler: /usr/lib64/ccache/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found TBB: /usr/include  
-- VTune profiling environment is unset
-- Found PythonInterp: /usr/bin/python (found version "3.7.2") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/seanvk/dev/oidn/build

[error.log](https://github.com/OpenImageDenoise/oidn/files/2823855/error.log)

**Comment by seanvk** [comment]
Attached file has the error log

**Comment by atafra** [comment]
This looks like a compiler bug. I don't see anything wrong with the code. It would be best to submit this bug to the GCC developers. Thanks!

**Comment by seanvk** [comment]
Yes, we ended up patching gcc distro.
