### ISSUE TITLE
Command 'tests' conflicts with other software libraries

### ISSUE THREAD

**Issue by jasonliu--** [OpenImageDenoise/oidn#64]
Hello, I'm currently working on packaging OIDN for the MacPorts package manager. In the course of creating and testing my package, I received the following error message from the MacPorts build system:

`Error: Failed to activate oidn: Image error: /opt/local/bin/tests is being used by the active libde265 port.  Please deactivate this port first, or use 'port -f activate oidn' to force the activation.`

Of course, what this means is that OIDN's `tests` command conflicts with an identically-named command created by @strukturag's [libde265](https://github.com/strukturag/libde265) library. Is there any possibility of changing the name of the `tests` command to be something less generic? I think maybe something like `oidn-tests` would make sense?

**Comment by atafra** [comment]
Hi! We'll consider renaming the commands in the next release, but these are actually only example applications for developers, and I don't think these are essential to have in a MacPorts package. So I think it would be acceptable to simply disable the `OIDN_APPS` CMake option, which will disable building these commands. This could be later turned on when we'll rename the commands. What do you think? Thanks!

**Comment by atafra** [comment]
We've renamed the commands to `oidnTest`, `oidnDenoise`, etc. It's currently available in the `devel` branch.

**Comment by jasonliu--** [comment]
Ok, that's great, thanks so much! I can backport this into the MacPorts package of OIDN 1.2.0 as a patch, until you release a new version of OIDN.

**Comment by atafra** [comment]
We've released `v1.2.1`, which includes the renamed commands.

**Comment by jasonliu--** [comment]
Awesome, thanks!
