### ISSUE TITLE
RTLightmap filter type and Albedo or Normal AOV

### ISSUE THREAD

**Issue by Dade916** [OpenImageDenoise/oidn#67]
I'm testing OIDN "RTLightmap" filter type with LuxCoreRender baked light maps and it seems to work well.

I was wondering if Albedo or Normal AOV are of any help to improve the denoising process like they are with "RT" filter type. I assume the Albedo is not but the normal one ?

**Comment by atafra** [comment]
Only the normals would be useful for lightmaps but so far the results have been a mixed bag: minor improvements here and there but also more artifacts popped up in other cases. We'll probably revisit this in the future.

**Comment by Dade916** [comment]
Ok, thanks.
