### ISSUE TITLE
Is ISPC a must?

### ISSUE THREAD

**Issue by jiapei100** [OpenImageDenoise/oidn#68]
It looks **ISPC** is required by oidn ?

**Comment by atafra** [comment]
Yes, ISPC is required for building Open Image Denoise.

**Comment by nijatmursali** [comment]
Hello, I'm having problem while building and it gives `Could not find ISPC.  Exiting.`. Could you please tell how we can install it?

**Comment by jomeng** [comment]
You can find ISPC at the official website: https://ispc.github.io/downloads.html
