### ISSUE TITLE
failed building on linux

### ISSUE THREAD

**Issue by FaraoniLuca** [OpenImageDenoise/oidn#69]
error logs:

CMake Warning (dev) at /usr/local/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (TBB_DEBUG)
  does not match the name of the calling package (TBB).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindTBB.cmake:274 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:74 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Threading Building Blocks (TBB) with minimum version 2017.0 not found. (missing: TBB_DEBUG_LIBRARY TBB_DEBUG_LIBRARY_MALLOC) 
CMake Error: File /home/luca/Desktop/oidn/mkl-dnn/include/dnnl_config.h.in does not exist.
CMake Error at cmake/oidn_dnnl.cmake:13 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:83 (include)

CMake Error: File /home/luca/Desktop/oidn/mkl-dnn/include/dnnl_version.h.in does not exist.
CMake Error at cmake/oidn_dnnl.cmake:17 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:83 (include)

-- Setting target version 1.2.0
-- Found OpenImageIO: /usr/include  
-- Configuring incomplete, errors occurred!

**Comment by jomeng** [comment]
Thank you for your report. We are currently working on a number of improvements in this area. Can you provide some detail on your TBB version, and how it is installed in your system?

**Comment by FaraoniLuca** [comment]
I've installed it, as suggested, via apt-get.

sudo apt-get install libtbb-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libtbb-dev is already the newest version (2017~U7-8).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by yesilcimenahmet** [comment]
Hi ,
I get this error on Windows with CMake.

> Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
> CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
>   The package name passed to `find_package_handle_standard_args` (TBB_DEBUG)
>   does not match the name of the calling package (TBB).  This can lead to
>   problems in calling code that expects `find_package` result variables
>   (e.g., `_FOUND`) to follow a certain pattern.
> Call Stack (most recent call first):
>   cmake/FindTBB.cmake:274 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>   CMakeLists.txt:74 (find_package)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Error: File D:/oidn-master/mkl-dnn/include/dnnl_config.h.in does not exist.
> CMake Error at cmake/oidn_dnnl.cmake:13 (configure_file):
>   configure_file Problem configuring file
> Call Stack (most recent call first):
>   CMakeLists.txt:83 (include)
> 
> 
> CMake Error: File D:/oidn-master/mkl-dnn/include/dnnl_version.h.in does not exist.
> CMake Error at cmake/oidn_dnnl.cmake:17 (configure_file):
>   configure_file Problem configuring file
> Call Stack (most recent call first):
>   CMakeLists.txt:83 (include)
> 
> 
> Setting target version 1.2.0
> OpenImageIO not found in your environment. You can 1) install
>                               via your OS package manager, or 2) install it
>                               somewhere on your machine and point OPENIMAGEIO_ROOT to it. (missing: OPENIMAGEIO_LIBRARY) 
> Configuring incomplete, errors occurred!
> See also "D:/oidn-master/bin/CMakeFiles/CMakeOutput.log".
> See also "D:/oidn-master/bin/CMakeFiles/CMakeError.log".

**Comment by jomeng** [comment]
Having a look at this issue again, this is probably not related to  TBB but rather the mkl-dnn submodule. You have to clone the repository recursively, that is including submodules, using

```shell
git clone --recursive https://github.com/OpenImageDenoise/oidn.git
```
This is detailed in our documentation: https://github.com/OpenImageDenoise/oidn

Also please note that Git LFS is required for the current version of Open Image Denoise.
I'm going to close this issue for now, but please feel free to contact us with any further questions.

**Comment by yesilcimenahmet** [comment]
Thanks. It worked
