### ISSUE TITLE
Provide a toggle to build as a static library?

### ISSUE THREAD

**Issue by TomCrypto** [OpenImageDenoise/oidn#7]
Would it be possible to include an option to build the library as a static library? Just switching the SHARED to STATIC basically works (at least on Ubuntu 18.04) though there are a couple errors to fix in the install module.

**Comment by atafra** [comment]
Yes, we're planning to add this option soon (probably in the next release)!

**Comment by ColinChargyBentley** [comment]
Hi @atafra,
That's perfect. Will the static build be included in release binaries for all OS? Will the mkl-dnn and tbb lib will be enclosed in the provided static lib (or will still use dynamic linkage for those) ? And finally, ETA ? :)
Thanks!
Regards,
Colin Chargy

**Comment by atafra** [comment]
A CMake option (`OIDN_STATIC_LIB`) has been added to the `devel` branch and will be available in the next release. Note that you need at least CMake 3.13.0 for this option (due to a bug in earlier CMake versions).

We're not planning to include static binaries in the official release packages.
