### ISSUE TITLE
Failed building on Windows | dnnl_config.h.in does not exist and OpenImageIO

### ISSUE THREAD

**Issue by yesilcimenahmet** [OpenImageDenoise/oidn#71]
Hi ,
I get this error on Windows with CMake.

I also download the OpenImageIO library from github and show the src folder. But still cannot find this library.

> Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
> CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
> The package name passed to find_package_handle_standard_args (TBB_DEBUG)
> does not match the name of the calling package (TBB). This can lead to
> problems in calling code that expects find_package result variables
> (e.g., _FOUND) to follow a certain pattern.
> Call Stack (most recent call first):
> cmake/FindTBB.cmake:274 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
> CMakeLists.txt:74 (find_package)
> This warning is for project developers. Use -Wno-dev to suppress it.
> 
> CMake Error: File D:/oidn-master/mkl-dnn/include/dnnl_config.h.in does not exist.
> CMake Error at cmake/oidn_dnnl.cmake:13 (configure_file):
> configure_file Problem configuring file
> Call Stack (most recent call first):
> CMakeLists.txt:83 (include)
> 
> CMake Error: File D:/oidn-master/mkl-dnn/include/dnnl_version.h.in does not exist.
> CMake Error at cmake/oidn_dnnl.cmake:17 (configure_file):
> configure_file Problem configuring file
> Call Stack (most recent call first):
> CMakeLists.txt:83 (include)
> 
> Setting target version 1.2.0
> OpenImageIO not found in your environment. You can 1) install
> via your OS package manager, or 2) install it
> somewhere on your machine and point OPENIMAGEIO_ROOT to it. (missing: OPENIMAGEIO_LIBRARY)
> Configuring incomplete, errors occurred!
> See also "D:/oidn-master/bin/CMakeFiles/CMakeOutput.log".
> See also "D:/oidn-master/bin/CMakeFiles/CMakeError.log".

**Comment by jomeng** [comment]
I believe this is the same issue as https://github.com/OpenImageDenoise/oidn/issues/69#issuecomment-629213544. Please clone the repository recursively. You will find more information in our documentation at https://github.com/OpenImageDenoise/oidn.
