### ISSUE TITLE
Static Build on OSX fail to install mkldnn

### ISSUE THREAD

**Issue by melMass** [OpenImageDenoise/oidn#73]
Hi,

I can build the shared version without issue, but trying to build the static version using:

```
cmake .. -DOIDN_STATIC_LIB=ON
```

Results in the following error at configure time:
```ruby
CMake Error at cmake/oidn_install.cmake:21 (install):
  install TARGETS given target "mkldnn" which does not exist.
```

**Comment by atafra** [comment]
Thanks for reporting this issue, static build is indeed broken. The fix has been pushed to `devel` and we'll soon (in about a week) release `v1.2.1` which will include this fix.
