### ISSUE TITLE
Dataset inquiry?

### ISSUE THREAD

**Issue by jiapei100** [OpenImageDenoise/oidn#74]
Hi, I had everything successfully built, just about to test the effects with the [suggested image dataset](https://openimagedenoise.github.io/gallery.html). However, some of the current data are for **3D**, and ONLY a few of them are for **Denoise**.

Can you please give out a detailed example with a given dataset? Let' s just try:

```cosole
data
`-- rt_train
    |-- scene1
    |   |-- view1_0001.alb.exr
    |   |-- view1_0001.hdr.exr
    |   |-- view1_0004.alb.exr
    |   |-- view1_0004.hdr.exr
    |   |-- view1_8192.alb.exr
    |   |-- view1_8192.hdr.exr
    |   |-- view2_0001.alb.exr
    |   |-- view2_0001.hdr.exr
    |   |-- view2_8192.alb.exr
    |   `-- view2_8192.hdr.exr
    |-- scene2_000008spp.alb.exr
    |-- scene2_000008spp.hdr.exr
    |-- scene2_000064spp.alb.exr
    |-- scene2_000064spp.hdr.exr
    |-- scene2_reference.alb.exr
    `-- scene2_reference.hdr.exr
```

Where are these .exr images that we can try?

Thank you

**Comment by atafra** [comment]
Hi! The images included in the gallery are lossily compressed and lack additional buffers, so you cannot test denoising with them. What do you mean by "some of the current data are for 3D"?

The .exr images listed above do not exist anywhere, this is just an example to illustrate how the dataset directory structure should look like.
