### ISSUE TITLE
Crashes when using progress monitor callback

### ISSUE THREAD

**Issue by fluidray** [OpenImageDenoise/oidn#78]
When using the progress monitor callback to cancel the filtering operation, there is a crash. 

It looks like the issue is caused by throwing an exception inside the constructor or the destructor of the Progress class.

The problem seems to be solved by wrapping the update() function as such:

try { update(); } catch(...) {}

in both the constructor and the destructor.

**Comment by atafra** [comment]
Thanks for reporting this issue! We've just released `v1.2.2`, which fixes the crash.
