### ISSUE TITLE
CMAKE ISPC needs update

### ISSUE THREAD

**Issue by cgvirus** [OpenImageDenoise/oidn#83]
Hello, ISPC cmake can't detect upgrades (currently v 1.14.0) in Linux. Had to manually change it to V 1.14.0. Probably needs to be updated in the cmake.
Thanks.
O/S: Debian 10.

**Comment by jomeng** [comment]
Thank you for your report! We are currently evaluating this new ISPC version, and will add support if possible.

**Comment by atafra** [comment]
I think there's a misunderstanding here. Updating the CMake file is **not** required to detect ISPC upgrades. If ISPC is added to the `PATH` (either manually or as a result of installing it from a package manager) or the `ISPC_EXECUTABLE` CMake parameter is set, future versions of ISPC will be detected without making any changes to the CMake files.

What probably happens in this case is that the ISPC package was only extracted next to the Open Image Denoise source directory. Thus ISPC is not actually installed system-wide but Open Image Denoise has a convenience feature which tries to detect ISPC anyway, if it's only extracted. For this to work with future versions, an update to the CMake file is indeed necessary but this is just a convenience feature or not the primary way for detecting ISPC. We'll update the CMake file but meanwhile you can still use this new ISPC version if you either add ISPC to the `PATH` or set `ISPC_EXECUTABLE` when configuring the build.

**Comment by cgvirus** [comment]
@atafra what is the package name for ISPC in Debain? I tried apt search but could not find any.
Yes, it was extracted from ISPC downloadable given in the description. I am seeing that CMAKE has a newer version detecting mechanism didn't realize it is possible only if path is set.
Probably added documentation would be much more better.
Thanks.
