### ISSUE TITLE
Flexible build with filter selection

### ISSUE THREAD

**Issue by WilliamTambellini** [OpenImageDenoise/oidn#86]
Hi
Some softwares are not always  interested by all OIDN filters. 
In such case, disabling some filters allows to significantly reduce the size of the library and some memory considering that the models are not loaded from disk at runtime but embedded in the lib (release/libOpenImageDenoise.so.1.2.2) :  
- full build with all filters: 44MB
- build with only the RTLightmapFilter : 9MB

Would you mind if I prepare a PR to add new cmake option(s) on order to (either): 
- enable/disable RTFilter and/or RTLightmapFilter : example:  OIDN_RTFILTER ON/OFF and OIDN_RTLIGHTMAPFILTER ON/OFF (default ON)
or
- select which filter to include in the build : example: OIDN_FILTERS = ALL (default) | RTFilter | RTLightmapFilter

Ref: 
https://github.com/godotengine/godot/blob/master/thirdparty/oidn/patches/godot-changes-c58c5216.patch

Kind
W.

**Comment by atafra** [comment]
Hi,

Thanks for feedback! We'll implement this feature in the next major version (`1.3.0`).

Regards,
Attila

**Comment by WilliamTambellini** [comment]
Cool, tks.

**Comment by WilliamTambellini** [comment]
@atafra  Hi, has that one been included in 1.3.0:
https://github.com/OpenImageDenoise/oidn/blob/master/CHANGELOG.md
?

**Comment by atafra** [comment]
No, sorry, this feature has been postponed for the next release (which should be available sometime in March). Since `v1.3.0` there are multiple sets of weights for `RTLightmap` as well. Is it still sufficient for you to just disable the `RT` filter and keep both blobs for `RTLightmap`? Or do you need a more fine-grained control over each weight blob?

**Comment by atafra** [comment]
This feature is now implemented in `v1.4.0`.
