### ISSUE TITLE
White splotches and brighter colors with Blender 2.83 Cycles render using the Compositor OIDN node

### ISSUE THREAD

**Issue by franMarz** [OpenImageDenoise/oidn#88]
![white-splotches-1](https://user-images.githubusercontent.com/58062362/93634683-4a777a00-f9f1-11ea-8acf-645194f34cd0.jpg)
![white-splotches-2](https://user-images.githubusercontent.com/58062362/93634700-53684b80-f9f1-11ea-9821-f8896825e7a8.jpg)

As you can see in the first image, there are white splotches on the floor and all lamps of the ceiling are brighter, they have emission and many of them don't surpass 1 in either rgb channel.

I don't know if this issue is related to Blender, its Compositor, or OIDN.

The setup of the nodes in the Compositor is quite normal, like this:
![blender denoising compo](https://user-images.githubusercontent.com/58062362/93635878-4cdad380-f9f3-11ea-97c8-0c3937a7e584.JPG)

**Comment by atafra** [comment]
It's very hard to say what causes these issues because the result is a combination of multiple denoised images. This compositing is done by Blender, not by Open Image Denoise. To find out whether Open Image Denoise does something wrong, the inputs and outputs of each denoising node must be examined separately.

**Comment by franMarz** [comment]
I've been reviewing the saved passes and can't see any sign of the splotches on them, they only appear on the final image. I've reviewed other renders where this happened as well. Like here, in some parts of the roof of the following Church:
![Splotches-All-Saints-Church-1](https://user-images.githubusercontent.com/58062362/93636518-5ca6e780-f9f4-11ea-92d8-cb489214a39a.jpg)
![Splotches-All-Saints-Church-2](https://user-images.githubusercontent.com/58062362/93636542-60d30500-f9f4-11ea-88c3-f0db9e8daa8b.jpg)
Or the grass, on the left side of this image:
![Splotches-SRCH-1](https://user-images.githubusercontent.com/58062362/93637179-70068280-f9f5-11ea-8faf-137b76aa9d22.jpg)
![Splotches-SRCH-2](https://user-images.githubusercontent.com/58062362/93637185-739a0980-f9f5-11ea-8717-b3df3d4c6051.jpg)
Next, I'll try to render and use the denoiser directly, without going through the Compositor.

**Comment by franMarz** [comment]
Ok, there were indeed some asserts in some passes:
Combined not denoised:
![Combined not denoised](https://user-images.githubusercontent.com/58062362/94085308-ffea6900-fe07-11ea-9b13-2c9b3975c789.jpg)
Combined denoised (white splotches):
![Combined denoised](https://user-images.githubusercontent.com/58062362/94085317-05e04a00-fe08-11ea-9b9e-ca997befcf7b.jpg)
Environment pass not denoised (pure black):
![Environment pass not denoised](https://user-images.githubusercontent.com/58062362/94085330-0d9fee80-fe08-11ea-9550-3d91be84479e.jpg)
Environment pass denoised (strange details):
![Environment pass denoised](https://user-images.githubusercontent.com/58062362/94085344-1a244700-fe08-11ea-99be-69245fae03d9.jpg)

The problem seems to happen during the denoising of any pass that is pure black (like "environment" in pixels which aren't part of the background) because, after using the denoising node, these passes present details that cause the white splotches to appear after the sum of several of these originally black passes.
In Blender, there are information that is sent to the denoiser (albedo and normal) for better preserving detail. But I don't see anything especially strange after reviewing these passes in all cases I had, and I don't know how they interact with the base pass but, if it is pure black, I think that in no scenario any data should show up because of them.

**Comment by franMarz** [comment]
I'm eager to know whether this is a problem related to OIDN or I have to post it in the Blender bug tracker.

**Comment by atafra** [comment]
Thanks for the detailed description, it's very useful! This is indeed an issue related to OIDN but to be more specific it's related to the actual denoising algorithm that OIDN and other AI denoising libraries are using. This is not technically a bug but a limitation of the AI algorithm itself.

Which version of OIDN are you using? Recently, in `v1.2.1` we alleviated this issue significantly but it's not completely gone which is unfortunately not possible with this algorithm. I highly recommend upgrading to the latest version, which might fix this issue for your use case. If the artifacts are still visible, you could try denoising the problematic passes without using the albedo and normal passes. This would completely eliminate the issue but might result in lower overall quality.

With the latest version these artifacts should not be visible when denoising final composited frames. OIDN was not trained for denoising separate passes (even if it works well in general) so such artifacts can be still visible in such cases.

**Comment by franMarz** [comment]
Indeed, in Blender 2.90, with uses OIDN v1.2.1, the problem seems to be solved.
Combined denoised Blender 2.90:
![compositor denoised blender 2 9](https://user-images.githubusercontent.com/58062362/94315135-364bf380-ff82-11ea-9f81-ecdc09c1a799.png)
Environment pass denoised Blender 2.90 (clean):
![environment denoised blender 2 9](https://user-images.githubusercontent.com/58062362/94315153-3e0b9800-ff82-11ea-91e5-0beeb8ca6524.png)

Thank you so much for your explanation on the matter, I think I can close this issue now.

**Comment by atafra** [comment]
Awesome, I'm glad it works well now!
