### ISSUE TITLE
[SUGGESTION] Images/videos denoising support

### ISSUE THREAD

**Issue by forart** [OpenImageDenoise/oidn#93]
It would be extremely useful to use the powerfulness of Intel processors to obtain a performative open source comprehansive "denoising suite".

Some interesting resources:

- [Awesome-Denoise](https://github.com/oneTaken/Awesome-Denoise): All latest image/burst/video Denoising papers with code & citation published in top conference and journal.
- [Kai Zhang's repos](https://github.com/cszn): Image Restoration; Inverse Problems
- [BasicSR](https://github.com/xinntao/BasicSR): an open source image and video restoration toolbox based on PyTorch, such as super-resolution, denoise, deblurring, JPEG artifacts removal, etc.
- [MIRNet](https://github.com/tuvovan/MIRNet---Keras): Keras Implementation of MIRNet - SoTA in Image Denoising, Super Resolution and Image Enhancement
- [Deep Plug-and-Play Image Restoration](https://github.com/JiaxiongQ/Denoise): Deep Plug-and-Play Image Restoration (PyTorch)
- [FastDVDnet](https://github.com/m-tassano/fastdvdnet): A state-of-the-art, simple and fast network for Deep Video Denoising which uses no motion compensation.
- [FastTVD](https://github.com/Michael-Shamouilian/FastTVD): Fast Total Variation Denoising and Speckle Denoising Utilizing GPUs and Multi-Core CPUs
- [CondatTV](https://github.com/MarieRoald/condat_tv): Cython wrapper for the efficient TV denoising algorithm by [Laurent Condat](https://lcondat.github.io/).
- [Implementation of Stochastic Image Denoising](https://github.com/pornosaur/stochastic-image-denoising)
- [Baseline Image Denoiser](https://github.com/Sohambasu07/Baseline_Image_Denoiser): Baseline Autoencoder based Denoiser with symmetric skip connections
- [image-denoise](https://github.com/matlabf/image-denoise): to remove noise from a noisy image, so as to restore the true image.
- [Deep Residual Autoencoder for Real Image Denoising](https://github.com/yilmazdoga/Deep_Residual_Autoencoder_for_Real_Image_Denoising)
- [Matlab-Image-Denoise](https://github.com/AomanHao/Matlab-Image-Denoise)

Hope that inspires !

**Comment by atafra** [comment]
Thanks for the resources! We're continuously working on improving both image quality and speed. Stay tuned for further improvements in Intel Open Image Denoise!
