### ISSUE TITLE
Please support oneTBB

### ISSUE THREAD

**Issue by yurivict** [OpenImageDenoise/oidn#96]
They are replacing TBB with a new generation, oneTBB, and oidn fails to build:
http://box.martymac.org/FreeBSD-Packages/data/FBSD122amd64-tbb-migr/2021-01-13_22h35m17s/logs/errors/oidn-1.2.4.log

Thanks,
Yuri

**Comment by atafra** [comment]
Thanks! This should be already fixed in the `devel` branch (see https://github.com/OpenImageDenoise/oidn/issues/94).

**Comment by atafra** [comment]
Fixed in `v1.3.0`.
